name: HomelabPush

on: push
jobs:
  deploy:
    runs-on: homelab
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.92.2"
          extended: true

      - name: Build
        run: hugo
        
      - name: LS
        run: ls

      - name: Copy Public Folder
        run: cp -r public/* /var/www/html/jarrod.website/public_html/

