name: Deployment to AWS

on: push

jobs:  
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy website to WebbyDT1
        uses: appleboy/scp-action@master
        env:
          HOST: 65.128.213.245
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 4090
          KEY: ${{ secrets.KEY }}
        with:
          source: "dest/*"
          target: "/var/www/jarrod.website/public_html"
          strip_components: 1
